##
# Plugins
require:
  - standard

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  Include:
    - libexec/quran-audio/*
    - lib/quran-audio/**/*.rb
    - bin/*

##
# Enabled
Style/FrozenStringLiteralComment:
   Enabled: true

##
# Disabled
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/LambdaCall:
  Enabled: false
